### ISSUE TITLE
Communicate that this resource relies on undocumented functionality

### ISSUE THREAD

**Issue by samaaron** [raspberrypilearning/ultrasonic-theremin#2]
## Background
This is resource is *ace*, and is precisely the kind of __instrument making__ I'm working to not just enable but make fun with Sonic Pi. I have been working on this stuff for around a year and am almost there. During the design process I implemented a number of different approaches some of which I sneakily shipped into prior releases so I could work with some expert users to get more feedback before finalising on a design. Although the code was there for the prototypes, I didn't document or list them in the changelog so typical users weren't aware of them, and therefore start using them in their prototype state consequently struggling when the syntax/behaviour completely changed as I switched design.

## Problem
Unfortunately, this resource relies on such an experimental prototype feature: receiving OSC messages on port 4559.

This means that there are the following potential issues for resource users:

* This resource will only work on a specific version of Sonic Pi (~`2.11`). Previous versions and subsequent versions will *not* work with the syntax in this resource. 
* There is a huge `0.5s` latency introduced by Sonic Pi's timing system (necessary for accuracy). 

## Suggestions
I would suggest the following ways to address these issues: 

* Communicate clearly which version of Sonic Pi you've tested it to work on here: https://www.raspberrypi.org/learning/ultrasonic-theremin/requirements/
* Add the code `set_sched_ahead_time! 0.1` to the top of the code to reduce the latency to just `0.1s`. 

Thanks again for making a great Sonic Pi resource :-)
## Future
I have recently been working on this area of Sonic Pi extensively and have made some vast improvements internally and externally (it's now the same system that enables MIDI controllers to be used). I have therefore changed the syntax again - so this resource will need to be updated in synchronisation with the next version of Sonic Pi (as a heads up, this will hopefully be early July). The syntax is currently:

```
live_loop :listen do
    use_sched_ahead_time 0
    note = sync "/play_this"
    play note
end
```

I'm likely to change `use_sched_ahead_time` to something a little more clear and simple. 

The cool thing is using exactly this same code (just matching against a different OSC path) you'll also be able to handle events from any connected MIDI controllers - no extra configuration necessary :-)

**Comment by samaaron** [comment]
Also, for the future...

I've added an incoming OSC message log to Sonic Pi which you'll be able to enable in the preferences. This will print out any OSC messages that are received on port `4559`. This may be worth adding to the resource as an initial step to test that the Python OSC part has been configured correctly. 

Here's a demonstration of the incoming OSC log in action (bottom right):

https://youtu.be/NMmkI5Hf8WE

**Comment by MarcScott** [comment]
Thanks @samaaron. I'll add in about it being an undocumented feature and that it will only run on the latest versions of SP.
Once it's all integrated and no longer experimental, could you drop an issue here?
BTW python-osc is now part of the standard image

**Comment by samaaron** [comment]
A v3 deb will be sent to Raspberry Pi Trading tonight and released on their schedule.

In preparation of that release, it's pertinent to point out the modifications that this resource will need to be compatible with Sonic Pi's official OSC API.

Firstly, there is the new cue log window at the bottom right of the screen. This will automatically display incoming OSC messages - so it will be very easy to see if the Python part of the resource is functioning correctly.

Secondly, if the Python program is on a separate machine, you'll have to enable the ability to receive external OSC messages in the preferences. By default Sonic Pi will only accept OSC messages from localhost.

Thirdly, all incoming OSC messages are now placed into the new Time State system. You can call `get` to see the last message received and `sync` to wait for the next message. When operating on incoming OSC messages both will return a list.

Fourthly, to remove the latency added for accurate timing (which isn't needed when responding directly to externally timed events such as OSC from Python) you need to use `use_real_time`. 

Combining all this, your live loop should likely end up looking like this:

```
live_loop :listen do
    use_real_time
    note = sync "/play_this"
    play note[0]
end
```

**Comment by MarcScott** [comment]
Thank you Sam. I'll make sure I update this on the next release of Raspbian.

**Comment by samaaron** [comment]
I should also point out that by default Sonic Pi will *not* accept incoming OSC messages from other computers. If the Python program is running on a different machine, then you need to enable the OSC preference "receive remote OSC messages" as illustrated here:

<img width="577" alt="screen shot 2017-08-01 at 13 21 33" src="https://user-images.githubusercontent.com/369/28824970-5c94ac46-76bc-11e7-9848-7f3fe0318ca7.png">

**Comment by samaaron** [comment]
(of course, this also means that if you have multiple computers on the same network, they can all be sending OSC messages to and from each other to enable all sorts of fun)

**Comment by samaaron** [comment]
Hi there, this resource is still in need of updating to match the official released OSC API in v3 of Sonic Pi. There are now people reporting issues in the wild: 

https://twitter.com/carmelhowe/status/934458995288563714
https://twitter.com/carmelhowe/status/934459491894071302

**Comment by MarcScott** [comment]
Hi @samaaron 
Looking to fix this today, although the ultrasonic is broken in gpiozero so will still cause issues!
Can I confirm that the only change I need to make is changing
```ruby
live_loop :listen do
    message = sync "/play_this"
	note = message[:args][0]
	play note
end
```

to

```ruby
live_loop :listen do
    use_real_time
    note = sync "/play_this"
    play note[0]
end
```

**Comment by samaaron** [comment]
From a code perspective this looks like all you need to change - but I’d definitely test it before pushing out :)

However, I would also be tempted to mention the new cue log in Sonic Pi which will allow you to visualise incoming OSC messages without having to write a single line of code. This will be very useful to test whether incoming messages are being received at all. 

Additionally I would mention that by default Sonic Pi will not accept messages from other machines on the network without explicitly enabling this in the preferences. 

Finally I might say a sentence or two about the function `use_real_time` perhaps referencing the built-in docs :)

Thanks!

**Comment by MarcScott** [comment]
Okay, thanks Sam. I'll have a test of it tomorrow and make the changes.
Sam Aaron writes:

> From a code perspective this looks like all you need to change - but I’d definitely test it before pushing out :)
>
> However, I would also be tempted to mention the new cue log in Sonic Pi which will allow you to visualise incoming OSC messages without having to write a single line of code.
> This will be very useful to test whether incoming messages are being received at all.
>
> Additionally I would mention that by default Sonic Pi will not accept messages from other machines on the network without explicitly enabling this in the preferences.
>
> Finally I might say a sentence or two about the function use_real_time perhaps referencing the built-in docs :)
>
> Thanks!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Marc Scott

Content & Curriculum Manager
Raspberry Pi Foundation
