### ISSUE TITLE
Potential error in code. 

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/ultrasonic-theremin#9]
User feedback: Within the live_loop added to Sonic Pi the sync path needs to be modified. It needs to be "/osc*/play_this".

On my Pi what is returned from the Python script is "/osc:127.0.0.1:50330/play_this". Leaving the original path in there resulted in no sound.

https://projects.raspberrypi.org/en/projects/ultrasonic-theremin/5

**Comment by MarcScott** [comment]
Changed to tonal buzzer
